### ISSUE TITLE
Generic interface for vendor specific DTC information

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/gallia#225]
We can read the raw DTC messages stored on the ECU, but this is not very helpful.
The messages are identified by an ID, which is vendor specific.
The idea is to provide a generic interface, to store a vendor specific DTC message catalog in the database.
This catalog could then be used by the DTC Scanner to display meaningful error messages.

**Comment by rumpelsepp** [comment]
Which dataformat is useful? A JSON file?
