### ISSUE TITLE
TargetURIs no longer have a _str_ method

### ISSUE THREAD

**Issue by ferdinandjarisch** [Fraunhofer-AISEC/gallia#440]
[e7ad26d7173314a5e84f1fc74a0b0a9c6101a7bc](https://github.com/Fraunhofer-AISEC/gallia/commit/e7ad26d7173314a5e84f1fc74a0b0a9c6101a7bc#diff-9690a4906eb0e5bde22c465875c7552073316a0d56a7d304eb177e6c46ff396bL86-L87)

@rumpelsepp pls explain

**Comment by rumpelsepp** [comment]
IIRC the TargetURI class was copied around by accident and cleaned up afterwards. Anyhow, please just add the desired method.
