### ISSUE TITLE
Reuse Code in Github Actions

### ISSUE THREAD

**Issue by rumpelsepp** [Fraunhofer-AISEC/gallia#6]
The current Github Actions configs share some copy & pasted code. Clean this up and find out how to reuse code snippets.

**Comment by oxisto** [comment]
Unfortunately, this won't be that easy, as GitHub actions do not support YAML anchors. The only way would probably be a custom action. It might help to integrate the separate workflows into one workflow with different steps (which can dependent on each other).

**Comment by rumpelsepp** [comment]
Unfortunate… :/
Then it might help to merge them, yes. I still need to read the docs for GH actions. I am used to use Gitlab-CI. :sweat_smile:

**Comment by rumpelsepp** [comment]
Maybe this could help: https://docs.github.com/en/actions/using-workflows/reusing-workflows
