### ISSUE TITLE
Wire up CI with virtual ECU

### ISSUE THREAD

**Issue by rumpelsepp** [Fraunhofer-AISEC/gallia#83]
Depends on #82

**Comment by rumpelsepp** [comment]
I created #113. We need to discuss what exactly the virtual ECU tests should cover. Especially what the scanners should do if a service is not available. :D

**Comment by peckto** [comment]
> I created #113. We need to discuss what exactly the virtual ECU tests should cover. Especially what the scanners should do if a service is not available. :D

For a first release, I think it's sufficient to just detect any crashes.
In the future, we can think about specific test-cases with reference behavior.
